// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Progress event sent through the StreamSink to Dart.
class PipelineProgress {
  final String stage;
  final double progress;

  const PipelineProgress({required this.stage, required this.progress});

  @override
  int get hashCode => stage.hashCode ^ progress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PipelineProgress &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          progress == other.progress;
}
