// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Process burst frames with live progress updates streamed to Dart.
///
/// Dart usage:
/// ```dart
/// final stream = captureAndProcess(frames: frames, sceneHint: "portrait");
/// await for (final update in stream) {
///   if (update.isComplete) {
///     // update.resultBytes contains the processed JPEG
///   } else {
///     // update.stage + update.progress for overlay
///   }
/// }
/// ```
Stream<ProcessingUpdate> captureAndProcess({
  required List<Uint8List> frames,
  String? sceneHint,
}) => RustLib.instance.api.crateApiImageApiCaptureAndProcess(
  frames: frames,
  sceneHint: sceneHint,
);

/// Process a single JPEG frame synchronously (no progress stream).
/// Used by capture_coordinator for fast mode.
Future<Uint8List> processSingle({
  required List<int> frame,
  String? sceneHint,
}) => RustLib.instance.api.crateApiImageApiProcessSingle(
  frame: frame,
  sceneHint: sceneHint,
);

Future<String> getEngineVersion() =>
    RustLib.instance.api.crateApiImageApiGetEngineVersion();

Future<Uint8List> processImageBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiImageApiProcessImageBytes(bytes: bytes);

Future<RoundtripResult> benchmarkRoundtrip({required List<int> bytes}) =>
    RustLib.instance.api.crateApiImageApiBenchmarkRoundtrip(bytes: bytes);

/// Progress update streamed to Dart during pipeline execution.
class ProcessingUpdate {
  final String stage;
  final double progress;
  final bool isComplete;
  final Uint8List resultBytes;
  final String error;

  const ProcessingUpdate({
    required this.stage,
    required this.progress,
    required this.isComplete,
    required this.resultBytes,
    required this.error,
  });

  @override
  int get hashCode =>
      stage.hashCode ^
      progress.hashCode ^
      isComplete.hashCode ^
      resultBytes.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessingUpdate &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          progress == other.progress &&
          isComplete == other.isComplete &&
          resultBytes == other.resultBytes &&
          error == other.error;
}

/// Returned by benchmark_roundtrip.
class RoundtripResult {
  final BigInt bufferSizeBytes;
  final BigInt rustProcessingUs;
  final bool passed;
  final String message;

  const RoundtripResult({
    required this.bufferSizeBytes,
    required this.rustProcessingUs,
    required this.passed,
    required this.message,
  });

  @override
  int get hashCode =>
      bufferSizeBytes.hashCode ^
      rustProcessingUs.hashCode ^
      passed.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoundtripResult &&
          runtimeType == other.runtimeType &&
          bufferSizeBytes == other.bufferSizeBytes &&
          rustProcessingUs == other.rustProcessingUs &&
          passed == other.passed &&
          message == other.message;
}
