// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../pipeline/orchestrator.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dto_to_config`

/// Engine version string — confirms .so loaded correctly.
Future<String> getEngineVersion() =>
    RustLib.instance.api.crateApiImageApiGetEngineVersion();

/// Process a single JPEG frame through the classical pipeline.
/// Returns processed JPEG bytes.
Future<Uint8List> processSingle({
  required List<int> frame,
  required PipelineConfigDto config,
}) => RustLib.instance.api.crateApiImageApiProcessSingle(
  frame: frame,
  config: config,
);

/// Process a burst of JPEG frames through the classical pipeline.
/// Returns processed JPEG bytes.
Future<Uint8List> processBurst({
  required List<Uint8List> frames,
  required PipelineConfigDto config,
}) => RustLib.instance.api.crateApiImageApiProcessBurst(
  frames: frames,
  config: config,
);

/// Process a burst with live progress updates streamed to Dart.
/// Returns Stream<PipelineProgress> in Dart.
Stream<PipelineProgress> processBurstWithProgress({
  required List<Uint8List> frames,
  required PipelineConfigDto config,
}) => RustLib.instance.api.crateApiImageApiProcessBurstWithProgress(
  frames: frames,
  config: config,
);

/// P2 passthrough — zero-copy validation.
Future<Uint8List> processImageBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiImageApiProcessImageBytes(bytes: bytes);

/// P2 benchmark — round-trip timing.
Future<RoundtripResult> benchmarkRoundtrip({required List<int> bytes}) =>
    RustLib.instance.api.crateApiImageApiBenchmarkRoundtrip(bytes: bytes);

/// Configuration DTO passed from Dart.
/// Maps 1:1 to ClassicalPipelineConfig.
class PipelineConfigDto {
  final bool runBurstStack;
  final bool runHdrMerge;
  final bool runExposureLift;
  final double exposureLiftAmount;
  final double saturation;
  final String toneMapping;
  final double sharpenAmount;
  final int jpegQuality;

  const PipelineConfigDto({
    required this.runBurstStack,
    required this.runHdrMerge,
    required this.runExposureLift,
    required this.exposureLiftAmount,
    required this.saturation,
    required this.toneMapping,
    required this.sharpenAmount,
    required this.jpegQuality,
  });

  static Future<PipelineConfigDto> default_() =>
      RustLib.instance.api.crateApiImageApiPipelineConfigDtoDefault();

  @override
  int get hashCode =>
      runBurstStack.hashCode ^
      runHdrMerge.hashCode ^
      runExposureLift.hashCode ^
      exposureLiftAmount.hashCode ^
      saturation.hashCode ^
      toneMapping.hashCode ^
      sharpenAmount.hashCode ^
      jpegQuality.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PipelineConfigDto &&
          runtimeType == other.runtimeType &&
          runBurstStack == other.runBurstStack &&
          runHdrMerge == other.runHdrMerge &&
          runExposureLift == other.runExposureLift &&
          exposureLiftAmount == other.exposureLiftAmount &&
          saturation == other.saturation &&
          toneMapping == other.toneMapping &&
          sharpenAmount == other.sharpenAmount &&
          jpegQuality == other.jpegQuality;
}

/// Returned by benchmark_roundtrip.
class RoundtripResult {
  final BigInt bufferSizeBytes;
  final BigInt rustProcessingUs;
  final bool passed;
  final String message;

  const RoundtripResult({
    required this.bufferSizeBytes,
    required this.rustProcessingUs,
    required this.passed,
    required this.message,
  });

  @override
  int get hashCode =>
      bufferSizeBytes.hashCode ^
      rustProcessingUs.hashCode ^
      passed.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoundtripResult &&
          runtimeType == other.runtimeType &&
          bufferSizeBytes == other.bufferSizeBytes &&
          rustProcessingUs == other.rustProcessingUs &&
          passed == other.passed &&
          message == other.message;
}
