// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Returns the Photonix engine version string.
/// Called at app startup to confirm the Rust library loaded correctly.
Future<String> getEngineVersion() =>
    RustLib.instance.api.crateApiImageApiGetEngineVersion();

/// Passes image bytes through the Rust engine and returns them.
/// In Phase 2 this is a passthrough — real processing added in P5/P6.
/// Vec<u8> is automatically zero-copied to Dart Uint8List in async mode.
Future<Uint8List> processImageBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiImageApiProcessImageBytes(bytes: bytes);

/// Benchmarks the Dart → Rust → Dart round trip for a given buffer.
/// Target: 4MB buffer must complete in under 5ms (5000 microseconds).
Future<RoundtripResult> benchmarkRoundtrip({required List<int> bytes}) =>
    RustLib.instance.api.crateApiImageApiBenchmarkRoundtrip(bytes: bytes);

/// Result struct returned by benchmark_roundtrip.
/// Timing fields are in microseconds for precision.
class RoundtripResult {
  /// Size of the buffer that was processed (bytes)
  final BigInt bufferSizeBytes;

  /// Total time from Rust receiving bytes to returning bytes (microseconds)
  final BigInt rustProcessingUs;

  /// Whether the round trip passed the 5ms threshold
  final bool passed;

  /// Human-readable result message
  final String message;

  const RoundtripResult({
    required this.bufferSizeBytes,
    required this.rustProcessingUs,
    required this.passed,
    required this.message,
  });

  @override
  int get hashCode =>
      bufferSizeBytes.hashCode ^
      rustProcessingUs.hashCode ^
      passed.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RoundtripResult &&
          runtimeType == other.runtimeType &&
          bufferSizeBytes == other.bufferSizeBytes &&
          rustProcessingUs == other.rustProcessingUs &&
          passed == other.passed &&
          message == other.message;
}
